export const GET_ERRORS = "GET_ERRORS";

export const GET_TEAMS = "GET_TEAMS";
export const GET_TEAM = "GET_TEAM";
export const DELETE_TEAM = "DELETE_TEAM";

export const GET_POSITIONS = "GET_POSITIONS";
export const DELETE_POSITION = "DELETE_POSITION";

export const GET_STATUSES = "GET_STATUSES";
export const DELETE_STATUS = "DELETE_STATUS";

export const GET_TYPESOFSECURITY = "GET_TYPESOFSECURITY";
export const DELETE_TYPEOFSECURITY = "DELETE_TYPEOFSECURITY";

export const GET_PAYMENTTYPES = "GET_PAYMENTTYPES";
export const DELETE_PAYMENTTYPES = "DELETE_PAYMENTTYPES";

export const GET_DOCUMENTTYPES = "GET_DOCUMENTTYPES";
export const DELETE_DOCUMENTTYPE = "DELETE_DOCUMENTTYPE";

export const GET_CLIENTTYPES = "GET_CLIENTTYPES";
export const DELETE_CLIENTTYPE = "DELETE_CLIENTTYPE";

export const GET_PRODUCTS = "GET_PRODUCTS";
